version: '3.8'

services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: gastrowise_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gastrowise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: gastrowise_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
